apiVersion: v1
kind: Service
metadata:
  name: wordsmith-service
  namespace: wordsmith
spec:
  type: LoadBalancer
  selector:
    app: wordsmith-jvm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080